name: Test CI

on:
  push:
#    tags:
#      - '*'

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest

    steps:
      # Checkout source files used by the Python checker
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: LIHPC-Computational-Geometry/spack_recipes_meshing
          path: spack_recipes_meshing

      - name: Test
        shell: bash
        run: |
          #git clone --depth=1 https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/LIHPC-Computational-Geometry/spack_recipes_meshing.git
          MESHING_RECIPES=$GITHUB_WORKSPACE/spack_recipes_meshing
          RECIPE_RELATIVE_PATH=meshing/packages/mgx/test.bidon
          #MESHING_RECIPES=$GITHUB_WORKSPACE
          #RECIPE_RELATIVE_PATH=test.bidon
          RECIPE_PATH=$MESHING_RECIPES/$RECIPE_RELATIVE_PATH
          echo Spack recipe: $RECIPE_PATH
          echo Project name: ${{ github.event.repository.name }}
          echo Project version: ${{ github.ref_name }}
          touch $RECIPE_PATH
          echo Add file $RECIPE_RELATIVE_PATH
          git -C $MESHING_RECIPES add $RECIPE_RELATIVE_PATH
          echo Commit and push for ${{ github.actor }}
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git -C $MESHING_RECIPES commit -m "Update recipe with new version"
          git -C $MESHING_RECIPES push

        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
