name: Test CI

on:
  push:
    tags:
      - '*'

jobs:
  call:
    name: Call check version CI
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/make-release-reusable.yml@main

