name: Test CI

on:
  push:
    tags:
      - '*'

jobs:
  call:
    name: Call check version CI
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/check-version-reusable.yml@main

# Create a Github Release
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          body: "**coucou** les amis"
#        env:
#          USERNAME: ${{ github.actor }}
#          PASSWORD: ${{ github.token }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
